// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForAddReservationSeats implements pgx.CopyFromSource.
type iteratorForAddReservationSeats struct {
	rows                 []AddReservationSeatsParams
	skippedFirstNextCall bool
}

func (r *iteratorForAddReservationSeats) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForAddReservationSeats) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ReservationID,
		r.rows[0].SeatID,
	}, nil
}

func (r iteratorForAddReservationSeats) Err() error {
	return nil
}

func (q *Queries) AddReservationSeats(ctx context.Context, arg []AddReservationSeatsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"reservation_seats"}, []string{"reservation_id", "seat_id"}, &iteratorForAddReservationSeats{rows: arg})
}

// iteratorForReserveFlightSeats implements pgx.CopyFromSource.
type iteratorForReserveFlightSeats struct {
	rows                 []ReserveFlightSeatsParams
	skippedFirstNextCall bool
}

func (r *iteratorForReserveFlightSeats) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForReserveFlightSeats) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].FlightID,
		r.rows[0].SeatID,
		r.rows[0].Availability,
	}, nil
}

func (r iteratorForReserveFlightSeats) Err() error {
	return nil
}

func (q *Queries) ReserveFlightSeats(ctx context.Context, arg []ReserveFlightSeatsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"flight_seats"}, []string{"flight_id", "seat_id", "availability"}, &iteratorForReserveFlightSeats{rows: arg})
}
