// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: reports.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPopularFlights = `-- name: GetPopularFlights :many
SELECT f.departure_airport, f.arrival_airport, COUNT(s.seat_id) as seat_count
FROM flights f
JOIN flight_seats s ON f.flight_id = s.flight_id AND departure_datetime BETWEEN $1::string AND $2
GROUP BY f.departure_airport, f.arrival_airport
ORDER BY seat_count DESC
LIMIT 20
`

type GetPopularFlightsParams struct {
	StartDate string           `json:"start_date"`
	EndDate   pgtype.Timestamp `json:"end_date"`
}

type GetPopularFlightsRow struct {
	DepartureAirport string `json:"departure_airport"`
	ArrivalAirport   string `json:"arrival_airport"`
	SeatCount        int64  `json:"seat_count"`
}

func (q *Queries) GetPopularFlights(ctx context.Context, arg GetPopularFlightsParams) ([]GetPopularFlightsRow, error) {
	rows, err := q.db.Query(ctx, getPopularFlights, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPopularFlightsRow
	for rows.Next() {
		var i GetPopularFlightsRow
		if err := rows.Scan(&i.DepartureAirport, &i.ArrivalAirport, &i.SeatCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
