// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: reservations.sql

package db

import (
	"context"
)

const getCustomerReservations = `-- name: GetCustomerReservations :many
SELECT reservation_id, flight_id, firstname, lastname, email, reservation_datetime, status FROM reservations 
    WHERE email = $1 
    AND $2 = firstname 
    AND $3 = lastname
`

type GetCustomerReservationsParams struct {
	Email     string `json:"email"`
	Firstname string `json:"firstname"`
	Lastname  string `json:"lastname"`
}

func (q *Queries) GetCustomerReservations(ctx context.Context, arg GetCustomerReservationsParams) ([]Reservation, error) {
	rows, err := q.db.Query(ctx, getCustomerReservations, arg.Email, arg.Firstname, arg.Lastname)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reservation
	for rows.Next() {
		var i Reservation
		if err := rows.Scan(
			&i.ReservationID,
			&i.FlightID,
			&i.Firstname,
			&i.Lastname,
			&i.Email,
			&i.ReservationDatetime,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
